using System.Collections.Generic;
using System.Linq;
using AlbumApp.Models;

namespace AlbumApp.Utils
{
    public class AlbumDataSeeder
    {
        private AlbumContext Context { get; }

        public AlbumDataSeeder(AlbumContext context)
        {
            this.Context = context;
        }

        public void Seed()
        {
            SeedCountries();
        }

        private void SeedCountries()
        {
            if(Context.Countries.Any())
            {
                return;
            }

            Context.Countries.AddRange(countries);
            Context.SaveChanges();
        }

        private List<Country> countries = (new string[] {
                "Afghanistan",
                "Albania",
                "Algeria",
                "American Samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antigua and Barbuda",
                "Argentina",
                "Armenia",
                "Aruba",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Benin",
                "Bermuda",
                "Bhutan",
                "Bolivia",
                "Bonaire",
                "Bosnia and Herzegovina",
                "Botswana",
                "Brazil",
                "British Virgin Islands",
                "Brunei Darussalam",
                "Bulgaria",
                "Burkina Faso",
                "Burundi",
                "Cambodia",
                "Cameroon",
                "Canada",
                "Cape Verde",
                "Cayman Islands",
                "Central African Republic",
                "Chad",
                "Chile",
                "China PR",
                "Chinese Taipei",
                "Colombia",
                "Comoros",
                "Congo DR",
                "Congo",
                "Cook Islands",
                "Costa Rica",
                "Côte d'Ivoire",
                "Croatia",
                "Cuba",
                "Curaçao",
                "Cyprus",
                "Czech Republic",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "England",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Ethiopia",
                "Faroe Islands",
                "Fiji",
                "Finland",
                "France",
                "French Guiana",
                "FYR Macedonia",
                "Gabon",
                "Gambia",
                "Georgia",
                "Germany",
                "Ghana",
                "Gibraltar",
                "Greece",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guinea-Bissau",
                "Guinea",
                "Guyana",
                "Haiti",
                "Honduras",
                "Hong Kong",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran",
                "Iraq",
                "Israel",
                "Italy",
                "Jamaica",
                "Japan",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Korea DPR",
                "Korea Republic",
                "Kosovo",
                "Kuwait",
                "Kyrgyz Republic",
                "Laos",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macau",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Martinique",
                "Mauritania",
                "Mauritius",
                "Mexico",
                "Moldova",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Morocco",
                "Mozambique",
                "Myanmar",
                "Namibia",
                "Nepal",
                "Netherlands",
                "New Caledonia",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "Niue",
                "Northern Ireland",
                "Northern Mariana Islands",
                "Norway",
                "Oman",
                "Pakistan",
                "Palestine",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Qatar",
                "Republic of Ireland",
                "Réunion",
                "Romania",
                "Russia",
                "Rwanda",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Martin",
                "Saint Vincent and the Grenadines",
                "Samoa",
                "San Marino",
                "São Tomé and Príncipe",
                "Saudi Arabia",
                "Scotland",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Sint Maarten",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Sudan",
                "Spain",
                "Sri Lanka",
                "Sudan",
                "Suriname",
                "Swaziland",
                "Sweden",
                "Switzerland",
                "Syria",
                "Tahiti",
                "Tajikistan",
                "Tanzania",
                "Thailand",
                "Timor-Leste",
                "Togo",
                "Tonga",
                "Trinidad and Tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Turks and Caicos Islands",
                "Tuvalu ",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United States of America",
                "Uruguay",
                "US Virgin Islands",
                "Uzbekistan",
                "Vanuatu",
                "Venezuela",
                "Vietnam",
                "Wales",
                "Yemen",
                "Zambia",
                "Zanzibar",
                "Zimbabwe",
            }).Select(name => new Country() { Name = name }).ToList();
    }
}